
name: LaTeX Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-full

      - name: Compile LaTeX document
        run: |
          mkdir -p output
          pdflatex -output-directory=output src/main.tex

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-pdf
          path: output/main.pdf
